<a href="https://colab.research.google.com/github/Nisfah0706/A11.2025.15915_PMesin/blob/main/Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import library

import pandas as pd
import numpy as np

In [4]:
from google.colab import files
files.upload()

Saving BL-Flickr-Images-Book.csv to BL-Flickr-Images-Book.csv

{'BL-Flickr-Images-Book.csv': b'Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks\n000000206,,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000000206,British Library HMNTS 12641.b.30.\n000000216,,London; Virtue & Yorston,1868,Virtue & Co.,"All for Greed. [A novel. The dedication signed: A. A. A., i.e. Marie Pauline Rose, Baroness Blaze de Bury.]","A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000000216,British Library HMNTS 12626.cc.2.\n000000218,,London,1869,"Bradbury, Evans & Co.","Love the Avenger. By the author of \xe2\x80\x9cAll for Greed.\xe2\x80\x9d [The dedication signed: A. A. A., i.e. Marie Pauline Rose, Baroness Blaze de Bury.]","A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000000218,British Library HMNTS 12625.dd.1.\n000000472,,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the close of the twelfth century. By the author of \xe2\x80\x9cProposals for Christian Union\xe2\x80\x9d (E. S. A. [i.e. Ernest Appleyard])","A., E. S.","Appleyard, Ernest Silvanus.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000000472,British Library HMNTS 10369.bbb.15.\n000000480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it. By E. S. A. [i.e. Letitia Willgoss Stone.] Edited by ... J. H. Broome.]","A., E. S.","BROOME, John Henry.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000000480,British Library HMNTS 9007.d.28.\n000000481,"Fourth edition, revised, etc.",London,1875,William Macintosh,"[The World in which I live, and my place in it. By E. S. A. [i.e. Letitia Willgoss Stone.] Edited by ... J. H. Broome.]","A., E. S.","BROOME, John Henry.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000000481,British Library HMNTS 9006.ee.10.\n000000519,,London,1872,The Author,Lagonells. By the author of Darmayne (F. E. A. [i.e. Florence Emily Ashley]),"A., F. E.","ASHLEY, Florence Emily.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000000519,British Library HMNTS 12637.e.3.\n000000667,,"pp. 40. G. Bryan & Co: Oxford, 1898",,,"The Coming of Spring, and other poems. By J. A. [i.e. J. Andrews.]","A., J.|A., J.","ANDREWS, J. - Writer of Verse",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000000667,British Library HMNTS 011652.g.73.\n000000874,,London],1676,,"A Warning to the inhabitants of England, and London in particular ... By M. A. [i.e. Mary Adams.]",Rema\xca\xbf.,"ADAMS, Mary.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000000874,British Library HMNTS 11645.bb.42.\n000001143,,London,1679,,A Satyr against Vertue. (A poem: supposed to be spoken by a Town-Hector. [By John Oldham. The preface signed: T. A.]),"A., T.","OLDHAM, John.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000001143,British Library HMNTS 11602.ee.10.(2.)\n000001280,,Coventry,1802,Printed by J. Turner,"An Account of the many and great Loans, Benefactions and Charities, belonging to the City of Coventry ... A new edition. [The dedication signed: AB, CD, EF, GH, &c. By Edward Jackson and Samuel Carte.]",,"CARTE, Samuel.|JACKSON, Edward - Rector of Southam, and CARTE (Samuel)",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000001280,British Library HMNTS 1430.g.17.\n000001808,,Christiania,1859,,"Erindringer som Bidrag til Norges Historie fra 1800-1815. Anden Udgave ... Udgivet med nogle Rettelser og Till\xc3\xa6g af Christian C. A. Lange. Med Forfatterens Portraet, og hans Biographi af Amtmand J. C. Aall","AALL, Jacob.","AALL, J. C.|LANGE, Christian Christoph Andreas.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000001808,British Library HMNTS 9425.cc.37.\n000001905,,Firenze,1888,,Gli Studi storici in terra d\'Otranto ... Frammenti estratti in gran parte dall\' Archivio Storico Italiano ... a cura e spese di L(uigi) G(iuseppe) D(e) S(imone),"AAR, Ermanno - pseud. [i.e. Luigi Giuseppe Oronzo Mariano Raffaele Francesco Fortunato Felice de Simone.]","S., L. G. D.|SIMONE, Luigi Giuseppe Oronzo Mariano Raffaele Francesco Fortunato Felice de.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000001905,British Library HMNTS 10136.g.22.\n000001929,,Amsterdam,"1839, 38-54",,De Aardbol. Magazijn van hedendaagsche land- en volkenkunde ... Met platen en kaarten. [Deel 4-9 by P. H. W.],,"WITKAMP, Pieter Harme.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000001929,British Library HMNTS 10002.g.16-19.\n000002836,,Savona,1897,,Cronache Savonesi dal 1500 al 1570 ... Accresciute di documenti inediti pubblicate e annotate dal dott. G. Assereto,"ABATE, Giovanni Agostino.","ASSERETO, Giovanni.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000002836,British Library HMNTS 10136.h.24.\n000002854,,London,1865,E. Moxon & Co.,"See-Saw; a novel ... Edited [or rather, written] by W. W. Reade","ABATI, Francesco.","READE, William Winwood.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000002854,British Library HMNTS 12623.bbb.12.\n000002956,,Paris,1860-63,,"Ge\xcc\x81ode\xcc\x81sie d\'une partie de la Haute E\xcc\x81thiopie, revue et re\xcc\x81dige\xcc\x81e par R. Radau. fasc. 1-3","ABBADIE, Antoine Thompson d\'.","RADAU, Rodolphe.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000002956,British Library HMNTS 10096.i.19.\n000002957,,Paris,1873,,[With eleven maps.],"ABBADIE, Antoine Thompson d\'.","RADAU, Rodolphe.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000002957,British Library HMNTS 10095.i.13.\n000003017,"Nueva edicion, anotada ... y continuada ... por J. J. de Acosta y Calbo.",Puerto-Rico,1866,,"[Historia geogra\xcc\x81fica, civil y politica de la Isla de S. Juan Bautista de Puerto Rico, Dala a luz A. Valladares de Sotomayor.]","ABBAD Y LASIERRA, Agusti\xcc\x81n I\xcc\x81n\xcc\x83igo - Bishop of Barbastro","ACOSTA Y CALBO, Jose\xcc\x81 Julian de.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000003017,British Library HMNTS 10480.h.18.\n000003131,,New York,1899,W. Abbatt,"The Crisis of the Revolution, being the story of Arnold and Andre\xcc\x81 now for the first time collected from all sources, and illustrated with views of all places identified with it ... Illustrations from original photographs by E. S. Bennett, etc","ABBATT, William.","ANDRE\xcc\x81, John - Major|ARNOLD, Benedict.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000003131,British Library HMNTS 9603.g.14.\n000004598,,Hull,1814,The Author,Peace: a lyric poem. [With prefatory address by F. Wrangham?],"ABBOTT, Thomas Eastoe.","WRANGHAM, Francis.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000004598,British Library HMNTS 11641.f.1.\n000004884,,London,1820,J. Hatchard & Son,"Abdallah; or, The Arabian Martyr: a Christian drama, in three acts. [In verse.] [By Thomas Foster Barham, the Elder.]",,"BARHAM, Thomas Foster - the Elder",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000004884,British Library HMNTS 994.l.1.(7.)\n000004976,"[Another edition.] Abdollatiphi histori\xc3\xa6 \xc3\x86gypti compendium ... Partim ipse vertit, partim a Pocockio versum edendum curavit, notisque illustravit J. White. Arab. & Lat.",Oxonii,1800,"J. Cooke, etc.",[Abdollatiphi Histori\xc3\xa6 \xc3\x86gypti compendium. [With a Latin version by Edward Pocock the younger.] Arab. & Lat.],,"WHITE, Joseph - Canon of Christ Church",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000004976,British Library HMNTS 983.e.6.|British Library HMNTS 148.d.4.|British Library HMNTS G.15137.\n000005382,,London,"1847, 48 [1846-48]",Punch Office,"The Comic History of England ... With ... coloured etchings, and ... woodcuts, by John Leech","A\'BECKETT, Gilbert Abbott.","LEECH, John - Artist",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000005382,British Library HMNTS C.131.d.16.|British Library HMNTS 9505.d.3.\n000005385,[Another edition.] Illustrated by John Leech.,London,[1897?],"Bradbury, Agnew & Co.","[The comic history of England ... With twenty coloured etchings, and two hundred woodcuts. By John Leech.]","A\'BECKETT, Gilbert Abbott.","LEECH, John - Artist",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000005385,British Library HMNTS 9503.f.4.\n000005389,[Another edition.],London,[1897?],"Bradbury, Agnew & Co.",[The Comic History of Rome ... Illustrated by John Leech.],"A\'BECKETT, Gilbert Abbott.","LEECH, John - Artist",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000005389,British Library HMNTS 9039.i.11.\n000005432,,Milano,1893,,Signa: opera in tre atti [founded on the novel entitled: \xe2\x80\x9cSigna\xe2\x80\x9d by Ouida] ... Traduzione ritmica di G. Mazzucato,"A\'BECKETT, Gilbert Arthur - and RUDALL (H. A.)","MAZZUCATO, Giovanni Andrea.|RUDALL, H. A.|Ouida",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000005432,British Library HMNTS 11779.g.8.(10.)\n000006036,,London,1805,C. & R. Baldwin,"The Venetian Outlaw, a drama in three acts ... Translated [from the French translation of J. H. D. Zschokke\'s \xe2\x80\x9cAba\xcc\x88llino, oder der grosse Bandit\xe2\x80\x9d] and adapted to the English stage by R. W. Elliston",,"ELLISTON, Robert William.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000006036,British Library HMNTS 642.i.25.|British Library HMNTS 164.g.68.\n000006821,,Aberdeen,1837,J. Davidson & Co.,Description of the Coast between Aberdeen and Leith. [By William Duncan.]: Appendix,,"DUNCAN, William - Clerk of Police, Aberdeen",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000006821,British Library HMNTS 797.d.2.\n000007521,,Wien,1896,,Aus Kaukasischen La\xcc\x88ndern. Reisebriefe von H. Abich. Herausgegeben von dessen Witwe (A. Abich),"ABICH, Wilhelm Hermann.","ABICH, Adelai\xcc\x88de.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000007521,British Library HMNTS 10077.h.21.\n000007630,,Abingdon,1898,W. H. Hooke,Selections from the Municipal Chronicles of the Borough of Abingdon from A.D. 1555 to A.D. 1897. Edited by B. Challenor,,"CHALLENOR, Bromley.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000007630,British Library HMNTS 10352.dd.26.\n000008239,,Quebec,1899,L. J. Demers & Fre\xcc\x80re,"The Plains of Abraham, 1759, a spot sacred to the memory of Wolfe and Montcalm. An appeal to all Canada for the preservation of the Plains of Abraham as portion of the public domain",,"BROTANEK, Rudolf.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000008239,British Library HMNTS 10470.ff.20.\n000008435,,London,1892,Effingham Wilson & Co.,The Witwatersrand Gold Mines. A true and unvarnished account of their origin and progress ... Translated ... by H. C. Simonsen,"ABRAHAM, Fe\xcc\x81lix - Writer on Mining","SIMONSEN, H. C.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000008435,British Library HMNTS 7106.b.46.\n000008440,,London,1894,Effingham Wilson,The New Era of the Goldmining Industry in the Witwatersrand ... Translated from the German by H. C. Simonsen. With an authentic map of the fields,"ABRAHAM, Fe\xcc\x81lix - Writer on Mining","SIMONSEN, H. C.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000008440,British Library HMNTS 07108.g.6.\n000011361,,Leipzig,[1894-96,,"Tirol und Vorarlberg ... Mit ... einer Karte, zahlreichen Illustrationen, etc","ACHLEITNER, Arthur - and UBL (E.)","UBL, E.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000011361,British Library HMNTS 10201.g.13.\n000011852,,"pp. 40. W. Cann: Plymouth, [1876?]",,,"A Question of Holy Writ, suggested by a lecture on Buddha and Buddhism, delivered before the Literary Society of Exeter, by Lieut. Ackland, R.N., and answered in the following lines, etc. [By Joseph Plimsoll.]: Bible. Appendix. Miscellaneous","ACKLAND - Lieut., R.N","PLIMSOLL, Joseph.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000011852,British Library HMNTS 011650.k.89.(4.)\n000013074,,London,1899,W. Thacker & Co.,"A Summer in High Asia: being a record of sport and travel in Baltistan and Ladakh ... With an appendix on Central Asian trade by Capt. S. H. Godfrey ... Illustrated from drawings by the author, photographs, and a map of the route","ADAIR, Frederick Edward Shafto.","GODFREY, Stuart Hill.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000013074,British Library HMNTS 10077.d.27.|British Library OC V 3030\n000013364,,London,[1885],"Griffith, Farran & Co.","A Hand-book and History of Sidmouth from the Triassic period up to \xe2\x80\x9cNow.\xe2\x80\x9d By \xd7\x90\xd7\x93\xd7\x9d [Adam, i.e. P. O. Hutchinson]. Illustrated ... With map",,"HUTCHINSON, Peter Orlando.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000013364,British Library HMNTS 10358.g.35.(4.)|British Library HMNTS 10352.d.32.\n000014466,,London,[1860?],Adams & King,"The Historie of Eald Street, now called Old Street, with memoranda of the Parish of St. Luke and of the Chartreuse",,"KING - Printer, of Goswell Street",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000014466,British Library HMNTS 10352.i.24.\n000014703,,1845,1846,,First (-Third) Annual Report on the Geology of the State of Vermont,,"ADAMS, Charles Baker.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000014703,British Library HMNTS 1254.h.9.\n000015141,,London,1893,T. Fisher Unwin,The New Egypt. A social sketch. [Edited by J. W. Longsdon.],"ADAMS, Francis William Lauderdale.","LONGSDON, J. W.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000015141,British Library HMNTS 010096.e.61.\n000015146,,London,1894,T. Fisher Unwin,Tiberius: a drama ... With introduction by W. M. Rossetti,"ADAMS, Francis William Lauderdale.","ROSSETTI, William Michael.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000015146,British Library HMNTS 11781.gg.4.\n000016173,,enk,1817,"printed by W. Thorne, and published by J. Callow; J. Hunter; and J. Ridgway","Memoirs of the Life and Doctrines of the late John Hunter, Esq., etc","ADAMS, Joseph - M.D., F.L.S","HUNTER, John - F.R.S",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000016173,British Library HMNTS 982.c.27.|British Library HMNTS RB.23.b.4745.\n000016543,,London,1816,John Murray,"The Narrative of Robert Adams, a sailor, who was wrecked on the Western Coast of Africa, in the year 1810 ... With a map, etc. [Edited by S. Cock.]","Adams, Robert - Sailor","COCK, Simon.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000016543,British Library HMNTS 983.e.7.|British Library HMNTS 147.e.3.|British Library HMNTS G.2842.\n000016544,[Another edition.],Boston,1817,Wells & Lilley,"[The Narrative of Robert Adams, a sailor, who was wrecked on the Western Coast of Africa, in the year 1810 ... With a map, etc. [Edited by S. Cock.]]","ADAMS, Robert - Sailor","COCK, Simon.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000016544,British Library HMNTS 789.bb.21.\n000017602,,London,1897,J. Bowden,East End Idylls ... With an introduction by the Hon. and Rev. J. G. Adderley,"Adcock, Arthur St. John","ADDERLEY, James Granville - Hon",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000017602,British Library HMNTS 012625.i.5.\n000017752,,Upsali\xc3\xa6,[1833],,"Acta historiam regis Chistierni II. illustrantia. Quae ... pr\xc3\xa6side mag. Erico Gust. Geijer ... pro gradu philosophico p.p. P. A. Adde, etc","ADDE, Petrus Adolphus.","GEIJER, Erik Gustaf.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000017752,British Library HMNTS 9425.bb.13.\n000018173,[Another edition.] With a complete index. [With a portrait engraved by Hopewood.],London,1804,Vernor & Hood,"[The Works of the late Right Honourable Joseph Addison, Esq. ... The third edition, etc. [Edited by Thomas Tickell.]]: Works","ADDISON, Joseph - Right Hon","TICKELL, Thomas.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000018173,British Library HMNTS 12269.d.7.\n000018218,,Edinburgh,1859,James Nichol,The Poetical Works of Joseph Addison; Gay\'s Fables; and Somerville\'s Chase. With memoirs and critical dissertations by Rev. George Gilfillan: Two or more Works,"Addison, Joseph","Gilfillan, George",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000018218,British Library HMNTS 11603.f.1.\n000018347,,Yverdon,1777,,"L\'Esprit d\'Addisson, ou les Beaute\xcc\x81s du Spectateur, du Babillard et du Gardien, consistant principalement dans une collection des feuilles de Mr. Addisson, avec un pre\xcc\x81cis de sa vie. Ouvrage nouvellement traduit de l\'anglais par Mr. J. P. A: Essays from the Spectator, Guardian and Tatler","ADDISON, Joseph - Right Hon","A., J. P. - Mr",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000018347,British Library HMNTS 12270.pp.15.\n000018469,,Londini,1799,F. & C. Rivington,"Addisoni Epistola missa ex Italia\xcc\x82 ad illustrem Dominum Halifax, anno 1701. [A translation into Latin hexameter verse.] Auctore A. Murphy. (Addison\'s Letter to Lord Halifax.) Lat. & Eng: Miscellaneous Single Works","ADDISON, Joseph - Right Hon","MURPHY, Arthur.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000018469,British Library HMNTS 11647.f.44.(2.)\n000019340,,St. Petersburg,1827,,"Augustin Freiherr von Meyerberg und seine Reise nach Russland. Nebst einer von ihm auf diese Reise veranstalteten Sammlung von Ansichten, Gebra\xcc\x88uchen, Bildnissen u. s. w","ADELUNG, Friedrich von.","MAYER, Augustin - Baron von Mayerberg",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000019340,British Library HMNTS 10291.e.1.\n000020207,,Berlin,1866,,Studien zur Cultur-Geschichte Polens. Bd. 1,"ADLER, Carl - Writer on Poland","D\xc5\x82ugosz, Jan.",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000020207,British Library HMNTS 9475.bbb.21.\n000020960,,London,1853,Addey & Co.,"The Diary and Houres of the Ladye Adolie, a faythfulle childe. 1552. [Edited, or rather written, by Lady C. M. Pepys.]",,"PEPYS, Charlotte Maria - Lady",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000020960,British Library HMNTS 12620.d.7.\n000021119,,London,1874,Chapman & Hall,"Lays of Modern Oxford, by Adon. Illustrated by M. E. Edwards, F. Lockwood, and the author",,"EDWARDS, Mary Ellen.|LOCKWOOD, Frank - Sir",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000021119,British Library HMNTS 11650.g.9.\n000021430,,London,1790,J. Johnson,"Adriano; or, the first of June, a poem. By the author of The Village Curate [i.e. James Hurdis]",,"Hurdis, James",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum000021430,British Library HMNTS 11632.d.48.(2.)|British Library HMNTS 992.k.27.(3.)|British Library HMNTS 1508/379.(2.)\n000021782,,London,[1817.],J. Johnston,"The Adventures of a Post Captain. By a Naval Officer. [In verse.] With ... engravings, by Mr. Williams",,"WILLIAMS, Samuel - Wood Engraver",,,,,monographic,http://www.flickr.com/photos/britishlibrary/tags/sysnum0000217

In [5]:
# load data

df = pd.read_csv("BL-Flickr-Images-Book.csv")
df.head()

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [6]:
# periksa tipe datanya utk masing2 varibael/kolom/fitur dengan .dtypes

print(df.dtypes)

Identifier                  int64
Edition Statement          object
Place of Publication       object
Date of Publication        object
Publisher                  object
Title                      object
Author                     object
Contributors               object
Corporate Author          float64
Corporate Contributors    float64
Former owner               object
Engraver                  float64
Issuance type              object
Flickr URL                 object
Shelfmarks                 object
dtype: object

In [7]:
# melihat statistik dasar

df.describe()

         Identifier  Corporate Author  Corporate Contributors  Engraver
count  8.287000e+03               0.0                     0.0       0.0
mean   2.017344e+06               NaN                     NaN       NaN
std    1.190379e+06               NaN                     NaN       NaN
min    2.060000e+02               NaN                     NaN       NaN
25%    9.157875e+05               NaN                     NaN       NaN
50%    2.043707e+06               NaN                     NaN       NaN
75%    3.047430e+06               NaN                     NaN       NaN
max    4.160339e+06               NaN                     NaN       NaN

In [8]:
# melihat pada lima entri pertama

df.head()

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [9]:
# memilih kolom-kolom yang akan di drop

to_drop = ['Edition Statement',
           'Corporate Author',
           'Corporate Contributors',
           'Former owner',
           'Engraver',
           'Contributors',
           'Issuance type',
           'Shelfmarks']

In [10]:
# melakukan drop pada data yang dipilih

df.drop(to_drop, inplace=True, axis=1)

In [11]:
# inspeksi ulang DataFrame, kolom yang tidak diinginkan sudah dibuang

df.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [12]:
#df.drop(colums=to_drop, inplace=True)
# cek ulang data

df.head()

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [13]:
# cek nilai unik identifier

df['Identifier'].is_unique

True

In [14]:
# ganti indeks yang ada pada kolom menggunakan set_index

df = df.set_index('Identifier')
df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...

In [15]:
# akses record ke 206

df.loc[206]

# .loc[] --> seleksi dengan menggunakan label/bilangan bulat

Place of Publication                                               London
Date of Publication                                           1879 [1878]
Publisher                                                S. Tinsley & Co.
Title                                   Walter Forbes. [A novel.] By A. A
Author                                                              A. A.
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 206, dtype: object

In [16]:
#df.set_index('Identifier', inplace=True)

In [17]:
# menghitung frekuensi nilai objek

df.dtypes.value_counts()

object    6
Name: count, dtype: int64

In [18]:
# seleksi data dari 1905 dengan output hanya pada field tanggal publikasi

df.loc[1905:, 'Date of Publication'].head(10)

Identifier
1905           1888
1929    1839, 38-54
2836           1897
2854           1865
2956        1860-63
2957           1873
3017           1866
3131           1899
4598           1814
4884           1820
Name: Date of Publication, dtype: object

In [19]:
# menggunakan ekspresi reguler (Regex) tunggal untuk mengekstrak tahun publikasi

regex = r'^(\d{4})'

In [20]:
# jalankan regex di dataset

extr = df['Date of Publication'].str.extract(r'^(\d{4})', expand=False)
extr.head()

# expand=False: --> Jika Benar, kembalikan  DataFrame dengan satu kolom per grup tangkapan.
# Jika Salah, kembalikan Seri/Indeks jika ada satu  grup tangkapan atau DataFrame jika ada beberapa  grup tangkapan.

Identifier
206    1879
216    1868
218    1869
472    1851
480    1857
Name: Date of Publication, dtype: object

In [21]:
# mendapatkan versi numeriknya dengan perintah pd.to_numeric

df['Date of Publication'] = pd.to_numeric(extr)
df['Date of Publication'].dtype

dtype('float64')

In [22]:
# perhitungan pada nilai valid yang tersisa

df['Date of Publication'].isnull().sum() / len(df)

np.float64(0.11717147339205986)

In [23]:
# isi kolom 'Place of Publication'

df['Place of Publication'].head(10)

Identifier
206                                  London
216                London; Virtue & Yorston
218                                  London
472                                  London
480                                  London
481                                  London
519                                  London
667     pp. 40. G. Bryan & Co: Oxford, 1898
874                                 London]
1143                                 London
Name: Place of Publication, dtype: object

In [24]:
df.loc[4157862]

Place of Publication                                  Newcastle-upon-Tyne
Date of Publication                                                1867.0
Publisher                                                      T. Fordyce
Title                   Local Records; or, Historical Register of rema...
Author                      FORDYCE, T. - Printer, of Newcastle-upon-Tyne
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 4157862, dtype: object

In [25]:
df.loc[4159587]

Place of Publication                                  Newcastle upon Tyne
Date of Publication                                                1834.0
Publisher                                                Mackenzie & Dent
Title                   An historical, topographical and descriptive v...
Author                                              Mackenzie, E. (Eneas)
Flickr URL              http://www.flickr.com/photos/britishlibrary/ta...
Name: 4159587, dtype: object

In [26]:
# mendapatkan boolean mask

pub = df['Place of Publication']
london = pub.str.contains('London')
london[:5]

Identifier
206    True
216    True
218    True
472    True
480    True
Name: Place of Publication, dtype: bool

In [27]:
oxford = pub.str.contains('Oxford')

In [28]:
df['Place of Publication'] = np.where(london, 'London',
                                      np.where(oxford, 'Oxford',
                                               pub.str.replace('-', ' ')))
df['Place of Publication'].head()

Identifier
206    London
216    London
218    London
472    London
480    London
Name: Place of Publication, dtype: object

In [29]:
# menampilkan data

df.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Flickr URL
Identifier,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,http://www.flickr.com/photos/britishlibrary/ta...
216,London,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.",http://www.flickr.com/photos/britishlibrary/ta...